name: Update packages

env:
  DOTNET_VERSION: '3.1'                 # set this to the .NET Core version to use

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Update files
        run: |
          dotnet UpdateUpsteamApp.dll

      - name: GitHub Commit & Push
        uses: actions-js/push@v1.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          message: update package script from upstream

